### ISSUE TITLE
v5 mega-issue

### ISSUE THREAD

**Issue by akiraveliara** [DSharpPlus/DSharpPlus#1580]
# This issue tracks the development of version 5 of the library.

For each work item, issues/prs/branches as well as their assignees are listed below.

Other maintainers, feel free to add additional work items as you go.

[ ] Obsoleting CommandsNext and SlashCommands in favor of DSharpPlus.Commands - @OoLunar and @Instellate, at `commands`
[ ] Obsoleting VoiceNext, to be discussed
[ ] Nullability-annotating the libraries
[ ] Cleaning up code readability - partially @InFTord, #1572, more work required
[ ] Updating Rest and Gateway - partially @akiraveliara, at `fix/consolidate-rest`, more work required
[ ] Enabling OAuth2 usage

**Comment by Plerx2493** [comment]
Missing gateway events:

- [x] CHANNEL_TOPIC_UPDATE
- [x] VOICE_CHANNEL_STATUS_UPDATE
- [ ] GUILD_SOUNDBOARD_SOUND_CREATE
- [ ] GUILD_SOUNDBOARD_SOUND_UPDATE
- [ ] GUILD_SOUNDBOARD_SOUND_DELETE

Note: those events are not documented by discord yet

**Comment by akiraveliara** [comment]
missing audit log keys: `flags` in invite updates - currently undocumented

**Comment by Plerx2493** [comment]
Correctly handle `MessagePollVoteRemoved`

**Comment by akiraveliara** [comment]
## 5.0.0-alpha.1

- finishing up IoC integration:
  - [ ] sharded client support - @akiraveliara #1971 
  - [ ] new event dispatcher instead of `DiscordClient.Events.cs`; support for full-type events with DI
  - [ ] new compression system with ZSTD support
  - [ ] DSharpPlus.Commands IoC support
  - [ ] DSharpPlus.CommandsNext, SlashCommands and Interactivity should build

**Comment by akiraveliara** [comment]
# 5.0.0-alpha.next

large new features:
- [x] E2EE voice support - @akiraveliara #2404 
- [x] new scalable permissions to handle > 64 bit permission fields - @akiraveliara #2152 
- [x] zstd support in compression - @akiraveliara #2000 
- [ ] bring DI in event handlers support to DSharpPlus.Commands
- [x] #2055 - @akiraveliara  #2115 
- [ ] #2126 
- [x] webhook events support - @VelvetToroyashi , @Plerx2493 , @akiraveliara #2145 
- [x] usage analyzer - @Instellate #2154 
- [ ] rework DSharpPlus.Commands metadata as groundwork for further extension work

minor other improvements and features:
- [x] target .NET 9 - @akiraveliara #2152 
  - [x] fix CA2022 in ImageTool.cs
- [ ] `params ReadOnlySpan<T>` support wherever meaningful
- [x] use new locks throughout the library
- [ ] source-generate `DiscordApplicationCommand.WeakEquals.cs` (and any future similar files)
- [ ] rework DSharpPlus.Commands default error handler
- [x] improve RestClient error reporting
- [x] support for message forwarding - @DubyaDude #2100 
  - [x] support creating forwarded messages - @akiraveliara #2123 
- [x] support for modifying bot banners - @Plerx2493 #1970 
- [ ] support for avatar decorations - #2081 
- [ ] support for discord's soundboard - @Plerx2493 

bugfixes:
- [x] #2089 
- [x] #2127 
- [ ] #2128 
- [x] #2129 
- [x] #2136 
- [x] #2139 
- [x] #2140 
- [x] #2210 
- [ ] #2213
