### ISSUE TITLE
Required docs updates

### ISSUE THREAD

**Issue by Emzi0767** [DSharpPlus/DSharpPlus#671]
# Summary
The docs require a bit of touching up before the release.

# Details
Here's a list of work items that require completion before 4.0 release:

- [x] New logging is documented. The transition from 3.2 logging to 4.0 logging should also be documented. See #605 for details. (resolved in #674)
- [x] VoiceNext updates from #566 should be included. (resolved in 50eb633c)
- [x] Intents should be mentioned in the library somewhere, as well as in the upgrade guide. (resolved in #673)

If anything else comes to mind, do let me know.
